// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pd.Tasks.Persistence;

#nullable disable

namespace Pd.Tasks.Persistence.Migrations
{
    [DbContext(typeof(LocalDbContext))]
    partial class LocalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pd.Tasks.Application.Features.TaskManagement.Models.TaskModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HoursWorked")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 4, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Users reporting issues with password reset flow",
                            DueDate = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            HoursWorked = 0,
                            IsActive = true,
                            Status = 1,
                            Title = "Fix authentication bug"
                        },
                        new
                        {
                            Id = 13,
                            CompletedAt = new DateTime(2026, 4, 11, 18, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 4, 9, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cover task service with xUnit tests",
                            DueDate = new DateTime(2026, 4, 16, 12, 0, 0, 0, DateTimeKind.Utc),
                            HoursWorked = 6,
                            IsActive = false,
                            Status = 3,
                            Title = "Write unit tests"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 4, 11, 14, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create responsive login form for Prodash",
                            DueDate = new DateTime(2026, 4, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            HoursWorked = 0,
                            IsActive = true,
                            Status = 1,
                            Title = "Design login UI"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 4, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Reset EF Core migrations for fresh start",
                            DueDate = new DateTime(2026, 4, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            HoursWorked = 2,
                            IsActive = true,
                            Status = 2,
                            Title = "Database migration cleanup"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 4, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Implement filtering by status in dashboard",
                            DueDate = new DateTime(2026, 4, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            HoursWorked = 0,
                            IsActive = true,
                            Status = 1,
                            Title = "Add task filtering"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 4, 6, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Configure GitHub Actions for Prodash",
                            DueDate = new DateTime(2026, 4, 13, 12, 0, 0, 0, DateTimeKind.Utc),
                            HoursWorked = 4,
                            IsActive = true,
                            Status = 2,
                            Title = "Setup CI/CD pipeline"
                        },
                        new
                        {
                            Id = 18,
                            CompletedAt = new DateTime(2026, 4, 11, 18, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 4, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Document endpoints for task management",
                            DueDate = new DateTime(2026, 4, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            HoursWorked = 5,
                            IsActive = false,
                            Status = 3,
                            Title = "Write API documentation"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 4, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Implement dark theme toggle in UI",
                            DueDate = new DateTime(2026, 4, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            HoursWorked = 0,
                            IsActive = true,
                            Status = 1,
                            Title = "Add dark mode"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 4, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Improve EF Core query performance",
                            DueDate = new DateTime(2026, 4, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            HoursWorked = 2,
                            IsActive = true,
                            Status = 2,
                            Title = "Optimize queries"
                        });
                });

            modelBuilder.Entity("Pd.Tasks.Application.Features.UsersManagement.Models.UserModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserRole")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
